### ISSUE TITLE
2021.1 how to get video frame from gstreamer pipeline to be post-processing in gvapython by opencv? 

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/dlstreamer_gst#148]
I wish to use opencv to draw some icon or put watermark on the video frame through gvapython but I didn't found any documentation.

**Comment by nnshah1** [comment]
The data from the frame is a numpy array which can be handled natively by opencv (it is equivalent to a cv::mat). Please see this example. The frame call back has the same type as gvapython process_frame:

https://github.com/openvinotoolkit/dlstreamer_gst/blob/702d8e43ea9813e96373a0272b23874baf7cc402/samples/python/draw_face_attributes/draw_face_attributes.py#L38

**Comment by tankienleong** [comment]
My gvapython script is as below but it gives error:

![Capture](https://user-images.githubusercontent.com/25731934/97771857-2aa0ad80-1b7c-11eb-87b1-3e101f684cf7.JPG)


![Capture](https://user-images.githubusercontent.com/25731934/97771815-a6e6c100-1b7b-11eb-9c3d-2b58e5fd06d3.JPG)

**Comment by nnshah1** [comment]
@tankienleong - As a quick workardound can you add in a `videoconvert ! video/x-raw` in front of the gvapython element?

It looks like the specific map operation to make the data available is failing for  a vaapisurface - would need more investigation to root cause that - but the above elements should convert the vaapisurface to system memory for you as well. That will be required in any case to operate on it from `gvapython`.  

Can you share the pipeline, system information (GPU version), and media details (h264, h265, etc.) ?

**Comment by tankienleong** [comment]
@nnshah1  I get the same error after I add in the videoconvert ! video/x-raw 

rtspsrc protocols=tcp location=rtsp://127.0.0.1:8566/cam66 ! rtph264depay ! vaapih264dec ! gvapython module=gvapython3 ! vaapih264enc ! rtph264pay config-interval=1 name=pay0 pt=96

Processor i7-7700T
Intel HD Graphics 630 (Kaby Lake GT2) 
Intel iHD driver 19.3.1
Ubuntu 18.04.4
Openvino 2021.1

**Comment by nnshah1** [comment]
I'm able to reproduce the issue if I explicitly set the caps to VASurface.

```
"! video/x-h264 ! vaapih264dec ! video/x-raw(memory:VASurface) ! gvapython name=relay module=/home/video-analytics-serving/extensions/jpg2mqtt class=JPG2MQTT"
```

But when I insert `video/x-raw` the issue goes away:
```
"! video/x-h264 ! vaapih264dec ! video/x-raw ! gvapython name=relay module=/home/video-analytics-serving/extensions/jpg2mqtt class=JPG2MQTT"
```

The relates to mapping the buffer for writing (read only buffer works). 

Can you try adding `video/x-raw` explicitly in the pipeline?

**Comment by mliu2020** [comment]
Hi @tankienleong,

Does your problem solved by @nnshah1's suggestion?

Mark

**Comment by tankienleong** [comment]
Hi @nnshah1 @mliu2020 ,

After I added the video/x-raw, it still show the same error.

**Comment by mliu2020** [comment]
Hi, @tankienleong,

Sorry for the late response.

Using a virtual camera, I can run following pipeline without issue, but if I put "latency=0 protocols=tcp" after "rtspsrc", I got an unsupported stream error:
`gst-launch-1.0 rtspsrc location=rtsp://10.0.0.232:8654/simulated_camera_0_1604984065731158528.sdp ! queue ! rtpjitterbuffer latency=0 ! rtph264depay ! decodebin ! videoconvert ! video/x-raw ! autovideosink sync=false

gst-launch-1.0 rtspsrc location=rtsp://10.0.0.232:8654/simulated_camera_0_1604984405507494400.sdp ! queue ! rtpjitterbuffer latency=0 ! rtph264depay ! video/x-h264 ! vaapih264dec ! videoconvert ! video/x-raw ! autovideosink sync=false`

I believe the only thing missing in my pipeline is python file, if you can give me a test python file, I can have a try.

Mark

**Comment by tankienleong** [comment]
Hi @mliu2020 

I had attached the python file
[gvapython3_for_mliu.zip](https://github.com/openvinotoolkit/dlstreamer_gst/files/5522615/gvapython3_for_mliu.zip)

**Comment by mliu2020** [comment]
Thanks for the quick response, let me try to add this to above pipeline and see if the issue can be reproduced.

Mark

**Comment by mliu2020** [comment]
@tankienleong,

Yes, I can reproduce it by only added it to the pipeline:
`developer@developer-desktop:~$ gst-launch-1.0 rtspsrc location=rtsp://10.0.0.232:8654/simulated_camera_0_1605255349463857408.sdp ! queue ! rtpjitterbuffer latency=0 ! rtph264depay ! video/x-h264 ! vaapih264dec ! videoconvert ! video/x-raw ! gvapython module=/home/developer/Downloads/gvapython3_for_mliu.py ! autovideosink sync=false
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'autovideosink0-actual-sink-vaapi': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayGLX\)\ vaapidisplayglx1";
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://10.0.0.232:8654/simulated_camera_0_1605255349463857408.sdp
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request
Redistribute latency...
Caught SIGSEGV
Spinning.  Please run 'gdb gst-launch-1.0 20484' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
ERROR: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstVaapiSink:autovideosink0-actual-sink-vaapi: Output window was closed
Additional debug info:
../gst/vaapi/gstvaapisink.c(461): gst_vaapisink_x11_handle_events (): /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0/GstVaapiSink:autovideosink0-actual-sink-vaapi
Execution ended after 0:00:15.297272512
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
`
I will do some investigation,

Mark

**Comment by tankienleong** [comment]
@mliu2020 

Thanks for letting me know and I’ll wait to hear from you.

**Comment by mliu2020** [comment]
@tankienleong ,

Sorry for the late response, I did a brief research and first I commend following line from your code:
#    with frame.data() as mat:
#        print(type(mat)) # should be numpy array
The pipeline can run normally, this confirmed my assumption, the print() function interferes with gstpython framework. This should be reasonable since this python model doesn't own stdout. So I did following print test with different function and it works:
    sys.stdout.write('hello')
    sys.stdout.write('\n')
    sys.stdout.flush()

I believe you can replace print(type(mat)) with sys.stdout.xxx calls but you have to parse type mat in different way.

Mark

**Comment by nnshah1** [comment]
@mliu2020 The underlying issue is in the: "with frame.data() as mat" call, not the print(type(mat)) call.

**Comment by tankienleong** [comment]
Hi @mliu2020 

I agree with @nnshah1, the issue is how to get numpy array from frame.data() in gvapython.
For gvawatermark plugin, we need to set a callback (see code below) to get numpy array to perform custom drawing since it only can draw rectangle. 
In my opinion, gvapython should not have this kind of callback because the python file (for gvapython) cannot access the mat and all the code in python file need to put inside the callback. 

def pad_probe_callback(pad, info):
&nbsp;&nbsp;&nbsp;&nbsp;with util.GST_PAD_PROBE_INFO_BUFFER(info) as buffer:
&nbsp;&nbsp;&nbsp;&nbsp;caps = pad.get_current_caps()
&nbsp;&nbsp;&nbsp;&nbsp;frame = VideoFrame(buffer, caps=caps)
&nbsp;&nbsp;&nbsp;&nbsp;with frame.data() as mat:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(type(mat)) # mat is numpy array that can handle by cv2
&nbsp;&nbsp;&nbsp;&nbsp;return Gst.PadProbeReturn.OK

gvawatermark = pipeline.get_by_name("gvawatermark")
pad = gvawatermark.get_static_pad("src")
pad.add_probe(Gst.PadProbeType.BUFFER, pad_probe_callback)

**Comment by tankienleong** [comment]
@nnshah1 @mliu2020 
any update on this issue?

**Comment by mliu2020** [comment]
@tankienleong,

Sorry for the late response, I was busy on other issues and I think there are some issues.

Let me start move investigation now.

On the other hand, could you use pad function instead of gvapython for this application? You can start from the example ~/sample/python/draw_face_attributes? I confirmed if you put your call back in that framework, you should get correct numpy array.

Mark

**Comment by alekseyfa** [comment]
Hi @tankienleong

The `VideoFrame` object that is provided to you in `def frame_callback(frame: VideoFrame):` can map only system memory in current implementation. In your pipeline with `vaapih264dec`, in addition to the `video/x-raw` caps filter, you also need to add the `vaapipostproc` element to fully convert to system memory.

Could you try running your case with the pipeline below that uses **vaapipostproc**?
```
gst-launch-1.0 rtspsrc latency=0 protocols=tcp location=rtsp:://127.0.0.1:8566/cam66 ! rtph264delay ! video/x-h264 ! vaapih264dec ! vaapipostproc ! video/x-raw ! gvapython module=gvapython3 ! fakesink
```

**Comment by Shk-aftab** [comment]
rtspsrc location=rtsp://viewer:something@something.ddns.net:###/Streaming/channels/#01 latency=100 ! queue ! rtph264depay ! h264parse ! avdec_h264 ! autovideosink

**Comment by adranit** [comment]
resolved in 2021.4

**Comment by PavanKumar13** [comment]
> Hi @tankienleong
> 
> The `VideoFrame` object that is provided to you in `def frame_callback(frame: VideoFrame):` can map only system memory in current implementation. In your pipeline with `vaapih264dec`, in addition to the `video/x-raw` caps filter, you also need to add the `vaapipostproc` element to convert to system memory correctly.
> 
> Could you try running your case with the pipeline below that uses **vaapipostproc**?
> 
> ```
> gst-launch-1.0 rtspsrc latency=0 protocols=tcp location=rtsp:://127.0.0.1:8566/cam66 ! rtph264delay ! video/x-h264 ! vaapih264dec ! vaapipostproc ! video/x-raw ! gvapython module=gvapython3 ! fakesink
> ```

Hi @alekseyfa,

I tried running this pipeline ,

gst-launch-1.0 rtspsrc latency=0 protocols=tcp location=rtsp:://127.0.0.1:8566/cam66 ! rtph264delay ! video/x-h264 ! vaapih264dec ! vaapipostproc ! video/x-raw ! gvapython module=gvapython3 ! fakesink

but getting the below error,
WARNING: erroneous pipeline: no element "rtph264delay"

we are trying to replace videoconvert, as videoconvert is utilizing high CPU, we wanted to avoid the CPU throttling and looking for a GPU element which is similar to videoconvert. 

@alekseyfa can you please share your thoughts and suggestions, Thanks in advance.

**Comment by nnshah1** [comment]
@PavanKumar13 I believe you have a typo in the pipeline, `rtph264delay`, should be `rtph264depay`

**Comment by brmarkus** [comment]
@PavanKumar13 can you provide more details about what you want to focus on (after you fixed the typo), please?

Depending on the underlying HW (SoC-generation, GPU-generation) the HW-accelerated video-decoder in the GPU returns e.g. NV12 data, i.e. the plugin `vaapih264dec` usually returns NV12 "raw data"

In your given pipeline you use `vaapih264dec ! vaapipostproc ! video/x-raw` - depending on the underlying HW you might want to add more details to `video/x-raw`.

Would it be possible to use a C/C++ plugin instead of `gvapython` then you could even benefit from "GPU-zero-copy".

**Comment by VijayaKumarKamma** [comment]
Thank you @nnshah1  and @brmarkus  for prompt reply on @PavanKumar13   question. Let me give you more details what we are trying to do....
Our source is RTSP.
1)We are trying to get Render the processed feed through browser.
2)And Reduce  the CPU usage by using VAAPI.

**1st case :** 
We were working with two types of pipeline one is with **decodebin** and **videoconvert** flags (which works on CPU but rendering is absolutely fine), CPU is usage is very high as **videoconvert** works on CPU. And Browser shows proper processed feed...As we are passing the frame to Turbojpeg to encode to Browser, feed is continuous and core dump issues.

Example Pipeline :  **rtspsrc location=rtsp://admin:kspot123@10.90.6.136/stream0  latency=1 timeout=1000 ! decodebin !             videoconvert n-threads=4 ! capsfilter caps="video/x-raw,format=BGR" ! gvainference  ---------gvatrack tracking-type=short-term  name=gvainference ! queue silent=true max-size-buffers=1 leaky=upstream ! videoconvert ! queue silent=true max-size-buffers=1 leaky=upstream ! appsink max-buffers=1 drop=true**

**2nd case:**
The second pipeline  is with **vaapih264dec** and **vaapipostproc** flags (which works on GPU but rendering is not fine), CPU is usage is very low as **vaapipostproc** works on GPU. But the issue is with processed feed...As we are passing the frame to Turbojpeg to encode to Browser ....Browser is showing Gray colour frames and if i open multiple time core dump issue is coming.

Example Pipeline:
**rtspsrc location=rtsp://admin:kspot123@10.90.6.125/stream0  latency=1 timeout=1000 ! rtph264depay ! vaapih264dec ! gvainference  -------- ! gvatrack tracking-type=short-term  name=gvainference ! queue silent=true max-size-buffers=1 leaky=upstream ! vaapipostproc ! queue silent=true max-size-buffers=1 leaky=upstream ! vaapisink**

The browser output looks like  attached screen shot ----i wounder why the frame is showing 3 times in the display if you observe. 

![pipeline2](https://user-images.githubusercontent.com/49179585/205561277-246ce2a1-0f1e-4776-aa54-d15db2c924cf.png)



Thanks in advance. Hope the question is clear, Please let us know your views.

**Comment by VijayaKumarKamma** [comment]
Thank you @brmarkus  for your reply.

We have one more issue. That is ..If we run the pipeline on GPU or VPU, after a long run like (10 to 20 hrs ) the processing is getting slow down and frames are skipping. Even the processing is in real time but its very jerky.

At starting the pipeline works absolutely fine .....with constant load of detections and classifications. 

We have observed that,  its happening in both the combinations like videoconvert ... ! appsink or vaapipostproc ... ! ... vaapisink

What would be the reason for this kind of issue.

Example pipeline is 
**rtspsrc location=rtsp://admin:kspot123@10.90.6.142/stream0  latency=1 timeout=1000 ! rtph264depay ! video/x-h264 ! vaapih264dec ! gvainference model-instance-id=face_dface142 model=models/face/assets/face-detection-adas-0001.xml nireq=20 device=HDDL batch-size=0  inference-interval=5 ! queue silent=true max-size-buffers=1 leaky=upstream !         gvapython --------------------- ! queue silent=true max-size-buffers=1 leaky=upstream !         gvatrack tracking-type=short-term !  gvaclassify model-instance-id=-------- model=-------batch-size=0  nireq=20 object-class=face_rects device=HDDL reclassify-interval=5 ! queue silent=true max-size-buffers=1 leaky=upstream ! gvadetect model-instance-id=head_dface142 model=models/retail/assets/head.xml model-proc=/opt/kloudspot/vision/models/demographics/retail_head_proc.json nireq=20 batch-size=0   device=HDDL threshold=0.6 inference-interval=2 ! queue silent=true max-size-buffers=1 leaky=upstream !                 gvatrack tracking-type=short-term  name=gvainference ! queue silent=true max-size-buffers=1 leaky=upstream ! vaapipostproc ! queue silent=true max-size-buffers=1 leaky=upstream ! vaapisink**

**Comment by brmarkus** [comment]
Could be many things...

maybe heat/cooling - and the SoC/CPU/GPU/VPU is throttling-down as protection from overheating...
maybe due to memory-leaks and system is slowly running out of memory and operating-system starts to shuffle with virtual memory
maybe due to running out of storage space in case you record the video and/or create log-files and the OS starts defragmentation ´, or triggering SSD-drive health-related operations
maybe local network has varying bandwidth when colleagues from other timezones join the network or IT starts to trigger system-scans or triggering backups in the network
maybe the RTSP stream source machine has issues constantly providing the stream after many hours

Do you see gstreamer logging something - like when and why frames get dropped by gstreamer? gstreamer sometimes print something like "There may be a timestamping problem, or this computer is too slow" to the console.
You might need to increase log-/verbose-level for gstreamer while keeping it running.

**Comment by VijayaKumarKamma** [comment]
Thank you for the quick reply, 

**Below are the system specs.**
We are using 16 core CPU with 64 gb ram and Intel(R) UHD Graphics 750 [0x4c8a],  having lot of storage and connected with 2  of 8X Myriad  VPU s.
The number of rtsp streams we are running are 30 and of  resolution is 1080 P

Usage is 
The CPU is around  300 % for 1600% - Always ram usage is constant at starting but keep increase little bit after some hours.
GPU is 70 % always .
VPU is under 50 % always.

Suspecting the RAM usage---RAM  is keep increasing bit by bit but still have lot of RAM remaining to use -- by the time frames processing slowed down.

Overheating is not much for the system.

Can you please check above pipeline once again , if there would be any buffer is getting accumulated in the long run (Suspecting queues as well )?? Is the pipeline matching the state of the art ? 


Thanks in advance........

**Comment by VijayaKumarKamma** [comment]
Hi @brmarkus    along with above questions we have did an observation is that 

We have run below pipeline with 30 RTSP streams with only Gstreamer elements.

**rtspsrc location=rtsp://****:*****@********/stream0  latency=1 timeout=1000 ! rtph264depay ! vaapih264dec  name=gvainference ! queue silent=true max-size-buffers=1 leaky=upstream ! vaapipostproc ! queue silent=true max-size-buffers=1 leaky=upstream ! vaapisink**


At starting the RAM consumption was 5GB and VPU is at 0 %

But after few hours like 4 hours - the frames skipping and the Ram increased to 20 GB . 

That means the problem is with Gstreamer elements only looks like.
Can you please check the pipeline any thing we should use or we should not so that we can get optimal pipeline ? ....... 

Along with the above check we did that whether camera is able to give stream or not ....and we have found that the camera is able to give 3 more streams.

Thank you!!

**Comment by brmarkus** [comment]
Try to remove further variables from the equation.
Do you see the same, when
- using a local vidoe-file instead of a RTSP-stream
- using a different model
- using CPU or GPU (or another device you have available), or e.g. MULTI, or even AUTO
- removing the queues from the pipeline

For the engineering team doing a more deeper analysis you might need to share more details about the model you use, its architecture, used parameters, used model-proc-file.

The combination of installed components could play a role as well (OpenVINO, gstreamer, libva, media-driver, hddl-daemong, etc.).

**Comment by VijayaKumarKamma** [comment]
Hi @brmarkus , 
with this pipeline

rtspsrc location=rtsp://....  latency=1 timeout=1000   ! decodebin max-size-buffers=1 ! vaapipostproc  name=gvainference ! vaapipostproc   ! queue silent=true max-size-buffers=1 leaky=upstream ! vaapisink sync=false 

We have observed that logs are printing  **"There may be a timestamping problem, or this computer is too slow"**   this message when we set the vaapisink element property   sync=True (No lag in the browser rendering but memory leak is there.)

If we make  sync=False   not printing above message but browser rendering is very slow and cpu usage is very high. 

Could you please suggest us what would be the better way to use Sync  and vaapi elements.

**Comment by brmarkus** [comment]
Can you try with a local video-file first - and explicitly spelling out the video-decoder, e.g. `vaapih264dec` (instead of using `decodebin`), please?
Try with a as simple as possible pipeline:

    gst-launch-1.0 filesrc location=myfile.hs64 ! vaapih264dec ! vaapisink

Then trying to use `sync=false`.
Then adding color-space-conversion and/or post-proc.

And get a pipeline-graph created (via ENV variable `GST_DEBUG_DUMP_DOT_DIR`) for each experiment - to see the impact of the changes, and to change whether it is a wanted behavior (like wanted or unwanted color-space conversion).

You might need to consult a RTSP stream export and check with your specific type of video-stream and format, available bandwidth, GOP-structure, allowed jitter, max wanted buffers, etc.
