### ISSUE TITLE
When using vaapih264dec and gvadetect, I got wrong raw frame with YUV channels mismatched

### ISSUE THREAD

**Issue by b04505009** [openvinotoolkit/dlstreamer_gst#155]
I use gstreamer and vaapih264dec decoding h264 frames to raw frames, then pass those frames to gvadetect to do inference. However, when I use opencv cvtColor to convert image from NV12 back to RGB, I got wrong image which has some green lines on the top.  I have done some tests and the problem seems on gvadetect.

My test result:
- Worked:
  - "filesrc location=street.h264 ! h264parse ! vaapih264dec ! vaapipostproc ! videoconvert ! video/x-raw,format=NV12 ! appsink"
  - "filesrc location=street.h264 ! h264parse ! mfxh264dec ! videoconvert ! video/x-raw,format=NV12 ! appsink"
  - "filesrc location=street.h264 ! h264parse ! avdec_h264 ! videoconvert ! video/x-raw,format=NV12 ! appsink"
- Not Worked:
  - filesrc location=street.h264 ! h264parse ! vaapih264dec ! videoconvert ! video/x-raw,format=NV12 ! appsink
  - filesrc location=street.h264 ! h264parse ! vaapih264dec ! vaapipostproc ! videoconvert ! video/x-raw,format=NV12 ! gvadetect model=frozen_inference_graph_INT8.xml model_proc=ssd.json name=gvadetect ! appsink
  - filesrc location=street.h264 ! h264parse ! vaapih264dec ! vaapipostproc ! videoconvert ! video/x-raw,format=NV12 ! 
 gvadetect model=frozen_inference_graph_INT8.xml model_proc=ssd.json name=gvadetect ! vaapipostproc ! video/x-raw,format=NV12 ! appsink

Here are my test code:
https://hackmd.io/@b04505009/HyRj9qFID
https://hackmd.io/@b04505009/H1j-zUb5P

I also post an issue to gstreamer-vaapi 
https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/286

**Comment by mliu2020** [comment]
@b04505009,

Can you clarify "I use opencv cvtColor to convert image from NV12 back to RGB"?

I didn't see it in the code and I don't know why you did it. 

From the first case of "Not worked" list, this seems like a gstreamer-vappi issue. So that should be the right place.

Mark

**Comment by mliu2020** [comment]
@b04505009,

I doubt there are some artifact with OpenCV VideoCapture(), it is amazing that we can use this function to capture the video, very good.

So I want to check if the pipeline works without OpenCV, for example, you can run the problematic pipeline with gst-launch. 

Mark

**Comment by b04505009** [comment]
@mliu2020 ,

The problem is, this opencv code is just for testing and showing the issue. My real situation is to develop an app using c++ and dlstreamer. I would like to save snapshot after doing inference, so I use gst_pad_add_probe() to add a probe to gvadetect's source pad. The frame I got from the pad_probe_callback() has the same problem as shown in opencv test code, while the output from the final sink (e.g. xvimagesink, filesink) are just fine, which is a bit weird.
I guess the problem might be in gva elements' pre/post process, or data communication between CPU and GPU (because avdec_h264 and mfxh264dec work fine), but cannot sure where's the root cause.

**Comment by adranit** [comment]
Hi @b04505009 ,
gvadetect element does not change an original video buffer, just attaches meta-data with detection results to it.

What version of gstvaapi  and dl_streamer do you use?
As far as I understand xvimagesink in pipeline with gvadetect displays the right picture. Am I correct?
Could you try to use another color scheme?

**Comment by b04505009** [comment]
Hi @adranit ,
I'm using vaapi==1.16.2 and dl_streamer==2021.1.1 with gstreamer-vaapi-patch
Yes, xvimagesink display right, and I use vaapih264enc with filesink can get correct frames.

I used BGR format before, things went right at that time. But we found using NV12 (or other YUV format? Not tested yet) can get higher fps. thus we changed to use NV12.

Here shows the concept how I get frames in pad_probe_callback()
```c++
auto buffer = GST_PAD_PROBE_INFO_BUFFER(info);
if (buffer == NULL)
        return GST_PAD_PROBE_OK;
// Get capabilities describing media types currently configured on pad
GstCaps *caps = gst_pad_get_current_caps(pad);
if (!caps)
    throw std::runtime_error("Can't get current caps");
// Construct VideoFrame instance from GstBuffer and GstCaps
// GVA::VideoFrame controls particular inferenced frame and attached
// GVA::RegionOfInterest and GVA::Tensor instances
GVA::VideoFrame video_frame(buffer, caps);
// Get size of region of interest
gint width = video_frame.video_info()->width;
gint height = video_frame.video_info()->height;

// Map buffer and create OpenCV image
GstMapInfo map;
if (!gst_buffer_map(buffer, &map, GST_MAP_READ))
    return GST_PAD_PROBE_OK;

cv::Mat mat((int)(1.5*height), width, CV_8UC1, map.data);
cv::Mat mat2;
cv::cvtColor(mat, mat2, cv::COLOR_YUV2BGR_NV12);
```

**Comment by mliu2020** [comment]
Hi @b04505009,

Your issue seems is the same as https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/243 which has been fixed by GST VAAPI team, could you try the latest gstreamer? @haitao also added comment to https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/286

Did you try GST 1.16.3?

Mark

**Comment by b04505009** [comment]
Hi @mliu2020 ,
I installed gstreamer-vaapi 1.16.3, but the problem still remained.

**Comment by b04505009** [comment]
Hi @mliu2020 ,

I installed gstreamer-vaapi 1.16.3, but the problem still remained.

**Comment by mliu2020** [comment]
@b04505009,

Sorry for not being clear, as in @haitao suggest in [#286](https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/286), could you try GStreamer 1.18.1 or cherry-pick commit da008baa to GStreamer 1.16.2?

**Comment by b04505009** [comment]
@mliu2020 It's a bit tricky to use gstreamer 1.18 with openvino and dl_streamer. Could you give me some hints to make them compatible? Thanks a lot.

**Comment by mliu2020** [comment]
Hi @b04505009,

Sure, but let's make sure before we move on.

When you listed your failed cases, the first case is:
`filesrc location=street.h264 ! h264parse ! vaapih264dec ! videoconvert ! video/x-raw,format=NV12 ! appsink`, this tells me the problem is either in VAAPI or OpenCV;  since there are no DL streamer element in this case.

So if you are still seeing the issue happens in this pipeline, you should work with VAAPI team to resolve it. I believe the problem is the dump process didn't deal with stride very well.

Mark

**Comment by mliu2020** [comment]
Hi @b04505009,

It has been a while since we debugged, I just review the whole thread and post in VAAP GST.

The root cause is the wrong cropping to the raw frame at certain elements. As @adranit mentioned, DL Streamer elements doesn't have any logic to change the raw frame, the pipeline you list at the first post also showed this.

If you set gst_pad_add_probe() at the gvadetect sink pad, you should see it has the same problem.

Did you have a solution yet?

As I said, this is a cropping problem so it should be easy to find a work around to crop the area that has artifact.

Let me know if I can close this issue.

Mark Liu

**Comment by b04505009** [comment]
Hi @mliu2020,

I have a work around now, though it's somehow ugly.

I did not have a solution yet. I guess the problem may be related to how gstreamer keep frame in memory and its interaction with opencv, but I didn't do further debugging since this is now not my first priority task.

b04505009

**Comment by mliu2020** [comment]
Hi @b04505009,

I have submitted an issue at OpenCV project and hope to get their help. could you also follow it?

One question: which OpenCV version did you used?

Mark

**Comment by b04505009** [comment]
Hi @mliu2020,

Thank you for your helping to report this issue, I'll keep follow up.

I used OpenCV 4.5.1 from OpenVINO package.

b04505009

**Comment by mliu2020** [comment]
@b04505009,

Saw your post to OpenCV, I want to check on my side and see how to reproduce it and figure out who owns the problem at least. Please give me a few days and I will get you back.

Mark

**Comment by mliu2020** [comment]
I am trying to figure out the root cause and I believe I'd better to try VAAPI side first before adding DL Streamer.

I review the [VAAPI issue](https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/286), I tried He Yunyan's method by using your command line and I can reproduce what he said. Here is what I did.

I selected the first item from your "worked" and "not worked" list and replace the "applink" with "filesink"
`"gst-launch-1.0 filesrc location=street.h264 ! h264parse ! vaapih264dec ! vaapipostproc ! videoconvert ! video/x-raw,format=NV12 ! filesink location=test_worked.yuv`
`"gst-launch-1.0 filesrc location=street.h264 ! h264parse ! vaapih264dec !  videoconvert ! video/x-raw,format=NV12 ! filesink location=test_not_worked.yuv`

You should use [YUView](https://github.com/IENT/YUView) to view the output file. If you use ubuntu, you can do `sudo snap install yuview --bata`

Launch yuview and load the output file, for "test_worked.yuv", you set the resolution to 1920x1080, but "test_not_worked.yuv", you must set resolution to 1920x1088 for smoothly playing, if you set resolution to 1920x1080, the rendering will be corrupted.

I didn't try the other command yet but I am pretty sure the same results. The key part is, I used neither DL Streamer nor OpenCV. this is clear the VAAPI problem.

Can you try to reproduce this way?

Mark

**Comment by mliu2020** [comment]
This is the artifacts when apply the wrong resolution(1920x1080)
![wrong_resolution](https://user-images.githubusercontent.com/21691753/114970729-d5a5da80-9e2f-11eb-962c-3736a33680b3.png)
This is the correct image when apply the correct resolution(1920x1088)
![correct_resolution](https://user-images.githubusercontent.com/21691753/114970744-dc345200-9e2f-11eb-87ce-46e9912619ac.png)
Mark

**Comment by b04505009** [comment]
Hi @mliu2020,

I check your command and I can reproduce your result.

However, I did another experiment which add gvadetect after vaapipostproc, like
`gst-launch-1.0 filesrc location=street.h264 ! h264parse ! vaapih264dec ! vaapipostproc ! videoconvert ! video/x-raw,format=NV12 ! gvadetect model=ssd.xml model_proc=ssd.json ! filesink location=test_gvadetect.yuv`
Then the green strip comes out again

And adding a vaapipostproc after gvadetect like
`gst-launch-1.0 filesrc location=street.h264 ! h264parse ! vaapih264dec ! vaapipostproc ! videoconvert ! video/x-raw,format=NV12 ! gvadetect model=ssd.xml model_proc=ssd.json ! vaapipostproc ! videoconvert ! video/x-raw,format=NV12 ! filesink location=test_gvadetect_vaapipostproc.yuv`
cannot fix this.

Based on this result, I guess dl_streamer may also involve in this issue?

b04505009

**Comment by mliu2020** [comment]
@b04505009,

Yes, I can confirm this and sorry for the late response.

But the root cause is on VAAPI GST, and as you mentioned in [that issue](https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/286).

The reason is, the issue can be showed without DL Streamer. Because of the GStreamer magic negotiation process, any element could affect the pipeline during the initialization, I think DL Streamer is just a factor which trigger the issue. But when I dump the pipeline graph, I can't see the difference so I am not sure how I can find the changes in the pipeline which causes the problem.

Let me discuss this with GST VAAPI side and see if they have any insights.

Mark Liu

**Comment by b04505009** [comment]
@mliu2020 ,

Ok I understand.

I think you may also check gstreamer 1.18. I have tested it before and seems the problem was not fixed, but you can check it yourself and see if we got same result.

Thank you for your supporting.

b04505009

**Comment by mliu2020** [comment]
I had a discussion with VAAPI team and they agree to check it again, let's following that post first.

Mark

**Comment by mliu2020** [comment]
@b04505009,

Can you try the fix posted on !286 of VAAPI repo?

They did a brief test in the "not work" pipeline and confirmed.

Mark

**Comment by b04505009** [comment]
Hi @mliu2020 ,

I tried the patch on 1.16.3, and the the problem got fixed on the case that without dl_streamer. But the issue still remain after using dl_streamer elements in pipeline.

My test result:

Success
```
gst-launch-1.0 filesrc location=US.mp4 ! qtdemux ! h264parse ! vaapih264dec ! \
"video/x-raw,format=NV12" ! \
filesink location=US.yuv

gst-launch-1.0 filesrc location=US.mp4 ! qtdemux ! h264parse ! vaapih264dec ! vaapipostproc ! \
"video/x-raw,format=NV12" ! \
filesink location=US.yuv
```
Failed:
```
gst-launch-1.0 filesrc location=US.mp4 ! qtdemux ! h264parse ! vaapih264dec ! "video/x-raw,format=NV12" ! \
gvadetect model=ssd_pd_300x300.xml model_proc=ssd_pd_300x300.json pre-process-backend=opencv ! \
filesink location=US.yuv

gst-launch-1.0 filesrc location=US.mp4 ! qtdemux ! h264parse ! vaapih264dec ! "video/x-raw,format=NV12" ! \
gvadetect model=ssd_pd_300x300.xml model_proc=ssd_pd_300x300.json pre-process-backend=opencv ! \
vaapipostproc ! "video/x-raw,format=NV12" ! \
filesink location=US.yuv

gst-launch-1.0 filesrc location=US.mp4 ! qtdemux ! h264parse ! vaapih264dec ! vaapipostproc ! "video/x-raw,format=NV12" ! \
gvadetect model=ssd_pd_300x300.xml model_proc=ssd_pd_300x300.json pre-process-backend=opencv ! \
filesink location=US.yuv
```
b04505009

**Comment by mliu2020** [comment]
Thanks so much,

At this stage, we should follow the post on VAAPI. I think DL Streamer has the binary uses GST 1.16.2.

I am not sure if we should apply this patch to DL Streamer also. Let me check.

Mark

**Comment by mliu2020** [comment]
Hi @b04505009,

I think VAAPI folks had a fix to this function, the reason why the dl streamer element still failed is, DL Streamer still used 1.16.2 release, it must be back patched. According to VAAPI developer,  you have backport !427 and i298 to 1.16.2.

Can you confirm this?

Mark

**Comment by mliu2020** [comment]
@b04505009 ,

As Victor mentioned in [gst-vaapi #286](https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/286#note_902329), this is the issue with vaapiXXXdecs. It was fixed in GST version 1.16.3 and above. The work around is to use "vaapipostproc" and "vaapidecodebin".

There are several reasons why we don't fix it in current DL Streamer release:
- DL Streamer is using GST 1.16.2, we need effort to back port the patches.
- DL Streamer is part of OV release, we can only fix it in GitHub, so it would take effort to fix it in release package for both dev team and customer.
- You already have a work around and luckily, you can wait for next release.

Again, apology for not being able to fix this in the current release and I will make sure this will be fix in the future release.

Mark Liu

**Comment by mliu2020** [comment]
I have checked with dev team and confirmed the GST VAAPI will be upgraded in next OpenVINO release. I will submit a request internally to validate if this case is fixed.

Mark Liu

**Comment by adranit** [comment]
I suggest this issue was resolved in 2021.4 release because Gst VAAPI was upgraded to 1.18.3.
